#!/bin/bash
# CS 302, assignment #4 test script.

# ---------------------------------------------------------
# Initial checks.
#	Ensure executable file exists.

if [ -z $1 ]; then
	echo "Error, must provide executable file name."
	exit
fi

if [ ! -e $1 ] || [ ! -x $1 ]; then
	echo "Error, unable to find $1 executable file."
	exit
fi

# ---------------------------------------------------------
# Define script variables and function

bolded=`tput bold`
normal=`tput sgr0`

pause() {
	if [ "$1" = "skip" ]; then
		echo
	else
		echo
		echo -n "Press return to continue"
		read
		clear
	fi
}

# ---------------------------------------------------------
# Display initial page

clear
echo
echo
echo ${bolded}Assignment 4 - Error Testing Utility${normal}
echo
echo
echo
echo
echo "Note, this utility assumes the program is working or very"
echo "      close to working.  Testing on an incomplete"
echo "      program will not be useful."
echo
echo
echo
pause $2

# ---------------------------------------------------------
# Begin tests.

echo
echo "**********************************************************************"
echo
echo "Test (10x15):"
./$1 -h 10 -w 15 -f wallsFile1.txt -p > mazeFile1.txt
cat wallsFile1.txt | ./maze_ppm 5 | convert - maze1.jpg

if `diff mazeFile1.txt mazeMstr1.txt >/dev/null` ; then
	echo "  10x15 Maze Console Output Successful"
else
	diff mazeFile1.txt mazeMstr1.txt
fi

if `diff wallsFile1.txt wallsMstr1.txt >/dev/null` ; then
	echo "  10x15 Maze Walls File Successful"
else
	diff wallsFile1.txt wallsMstr1.txt
fi

if `diff maze1.jpg mazeMstr1.jpg >/dev/null` ; then
	echo "  10x15 Maze Image File Successful"
else
	diff maze1.jpg mazeMstr1.jpg
fi

echo
#
# -----
#
echo "Test (20x60):"
./$1 -h 20 -w 60 -f wallsFile2.txt -p > mazeFile2.txt
cat wallsFile2.txt | ./maze_ppm 5 | convert - maze2.jpg

if `diff mazeFile2.txt mazeMstr2.txt >/dev/null` ; then
	echo "  20x60 Maze Console Output Successful"
else
	diff mazeFile2.txt mazeMstr2.txt
fi

if `diff wallsFile2.txt wallsMstr2.txt >/dev/null` ; then
	echo "  20x60 Maze Walls File Successful"
else
	diff wallsFile2.txt wallsMstr2.txt
fi

if `diff maze2.jpg mazeMstr2.jpg >/dev/null` ; then
	echo "  20x60 Maze Image File Successful"
else
	diff maze2.jpg mazeMstr2.jpg
fi
#
# -----
#
echo
echo "Test (100x150):"
./$1 -h 100 -w 150 -f wallsFile3.txt -p > mazeFile3.txt
cat wallsFile3.txt | ./maze_ppm 5 | convert - maze3.jpg

if `diff mazeFile3.txt mazeMstr3.txt >/dev/null` ; then
	echo "  100x150 Maze Console Output Successful"
else
	diff mazeFile3.txt mazeMstr3.txt
fi

if `diff wallsFile3.txt wallsMstr3.txt >/dev/null` ; then
	echo "  100x150 Maze Walls File Successful"
else
	diff wallsFile3.txt wallsMstr3.txt
fi

if `diff maze3.jpg mazeMstr3.jpg >/dev/null` ; then
	echo "  100x150 Maze Image File Successful"
else
	diff maze3.jpg mazeMstr3.jpg
fi
#
# -----
#
echo
echo "Test (300x400):"
./$1 -h 300 -w 400 -f wallsFile4.txt -p > mazeFile4.txt
cat wallsFile4.txt | ./maze_ppm 5 | convert - maze4.jpg

if `diff mazeFile4.txt mazeMstr4.txt >/dev/null` ; then
	echo "  300x400 Maze Console Output Successful"
else
	diff mazeFile4.txt mazeMstr4.txt
fi

if `diff wallsFile4.txt wallsMstr4.txt >/dev/null` ; then
	echo "  300x400 Maze Walls File Successful"
else
	diff wallsFile4.txt wallsMstr4.txt
fi
if `diff maze4.jpg mazeMstr4.jpg >/dev/null` ; then
	echo "  300x400 Maze Image File Successful"
else
	diff maze4.jpg mazeMstr4.jpg
fi

echo
#
# -----
